### ISSUE TITLE
"Report Issue" bar blocks content

### ISSUE THREAD

**Issue by rcelyte** [xAphex/xAphex.github.io#6]
As you can see in this image, the bar covers the bottom row of buttons
![overlap](https://user-images.githubusercontent.com/25163630/39221216-83d88fe8-47ea-11e8-8bf8-aaee55539987.png)

**Comment by xAphex** [comment]
What's your screen resolution and what browser are you using?

**Comment by rcelyte** [comment]
1366x768, Opera (not sure about actual window height)

**Comment by redline2466** [comment]
Not sure about actual window height.

**Comment by xAphex** [comment]
**What's your screen size?**

The website works fine on 1366x768 resolution.

Guess you have a small screen size so everything looks compact.
