### ISSUE TITLE
Clear Ices download buttons are hidden

### ISSUE THREAD

**Issue by Underqualified-Gunman** [xAphex/xAphex.github.io#7]
![cliissue](https://user-images.githubusercontent.com/5576256/46899902-65cdc800-ce5f-11e8-9a23-954791554dfb.PNG)

was able to download the pack by doing inspect element and finding the right pack link

**Comment by xAphex** [comment]
After a very long and hassle fight with keeping the footer at the bottom, i officially give up.
footer, u win.

so yeah, i removed the footer.
